tags:
    - Profile
summary: Получение инвентаря
description: "Полчучение предметов в инвентаре пользователя"
operationId: getUserInventoryUsername
parameters:
    - name: username
      in: path
      description: "Имя пользователя"
      required: true
      style: form
      explode: false
      schema:
          type: string
responses:
    "200":
        description: Успешное получение инвенторя
        content:
            application/json:
                schema:
                    type: array
                    items:
                        $ref: ../../../../components/schemas/User/Games/Inventory.yaml
    "404":
        description: Пользователь не найден
security: []
